import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ...js.configs.recommended,
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser, // all standard browser APIs (atob, DOMParser, File, Event, etc.)

        // ── Store & persistence ──────────────────────────────────────────────
        store: "writable",
        saveStore: "readonly",
        loadStore: "readonly",
        openDB: "readonly",
        triggerAutoSave: "readonly",
        initAutoSave: "readonly",

        // ── Store helpers ────────────────────────────────────────────────────
        currentProject: "readonly",
        getProject: "readonly",
        defaultProject: "readonly",
        makeId: "readonly",
        relativeTime: "readonly",
        FILE_CATEGORIES: "readonly",
        fileCategories: "readonly",
        fileProjectIds: "readonly",
        getFileCategory: "readonly",
        getFileIcon: "readonly",
        formatFileSize: "readonly",
        BREAKDOWN_CATEGORIES: "readonly",
        CONTACT_BUILTIN_COLS: "readonly",
        LOCATION_BUILTIN_COLS: "readonly",
        UNIT_DEPTS: "readonly",
        EQUIP_CATEGORIES: "readonly",
        BD_SUGGEST_KEYWORDS: "readonly",

        // ── UI helpers ───────────────────────────────────────────────────────
        showToast: "readonly",
        showConfirmDialog: "readonly",
        showPromptDialog: "readonly",
        showContextMenu: "readonly",
        openModal: "readonly",
        closeModal: "readonly",
        loadTheme: "readonly",
        initTableScrollbars: "readonly",

        // ── Navigation / views ───────────────────────────────────────────────
        showView: "readonly",
        showProjectView: "readonly",
        showSection: "readonly",
        renderDashboard: "readonly",
        renderSidebarProjects: "readonly",
        renderProjectView: "readonly",
        renderOverview: "readonly",
        renderOverviewFiles: "readonly",
        renderSettings: "readonly",
        renderFiles: "readonly",
        renderScript: "readonly",
        renderBrief: "readonly",
        renderBreakdown: "readonly",
        renderStripboard: "readonly",
        renderCallsheet: "readonly",
        renderSchedule: "readonly",
        renderCast: "readonly",
        renderUnit: "readonly",
        renderBudget: "readonly",
        renderEquipment: "readonly",
        renderProjectLocations: "readonly",
        renderShotList: "readonly",
        renderPropTable: "readonly",
        renderWardrobeTable: "readonly",
        renderSoundLog: "readonly",
        renderRiskAssessment: "readonly",
        renderReleases: "readonly",
        renderCustomSection: "readonly",
        renderSection: "readonly",
        renderTechScouts: "readonly",
        renderTeam: "readonly",
        renderContacts: "readonly",
        renderLocations: "readonly",
        renderMoodboards: "readonly",
        addGearDay: "readonly",
        duplicateGearDay: "readonly",
        removeGearDay: "readonly",
        toggleGearCheck: "readonly",
        addGearItemToDay: "readonly",
        addGearCategoryToDay: "readonly",
        openUnsortedGear: "readonly",
        editGearDay: "readonly",
        exportGearPrint: "readonly",

        // ── Save handlers (called from HTML onsubmit/onclick) ────────────────
        saveProject: "readonly",
        savePersonnel: "readonly",
        saveBudgetLine: "readonly",
        saveLocation: "readonly",
        saveScheduleRow: "readonly",
        saveEquipItem: "readonly",
        saveInvite: "readonly",
        saveShot: "readonly",
        savePropItem: "readonly",
        saveWardrobeItem: "readonly",
        saveSoundEntry: "readonly",
        saveRiskRow: "readonly",
        saveAddCast: "readonly",
        saveCSCustomField: "readonly",
        saveStory: "readonly",
        saveContactColumns: "readonly",
        saveLocationColumns: "readonly",
        saveEditedContact: "readonly",
        saveLocationGlobal: "readonly",
        saveNewMoodboard: "readonly",
        saveMbVideo: "readonly",
        saveMbColor: "readonly",
        confirmManageFile: "readonly",
        confirmMoveFile: "readonly",
        confirmRemoveFiles: "readonly",
        confirmScriptUpload: "readonly",

        // ── Contacts ─────────────────────────────────────────────────────────
        populateContactSelect: "readonly",
        contactSubView: "writable",
        ecClearRoles: "readonly",
        ecToggleRoleSections: "readonly",
        ecAddRole: "readonly",
        ecGetRoles: "readonly",
        addSocialField: "readonly",
        collectSocials: "readonly",
        fullyRemoveFromProject: "readonly",
        isPersonStillInProject: "readonly",
        mfAddPersonTagDirect: "readonly",
        getFilesForPerson: "readonly",
        photoStripHTML: "readonly",
        photoStripContactHTML: "readonly",
        refreshRolesDatalist: "readonly",
        _cachedContacts: "writable",
        _pendingFullRemovals: "writable",
        expandedContacts: "writable",

        // ── Locations ────────────────────────────────────────────────────────
        getFilesForLocation: "readonly",
        toggleLocationExpand: "readonly",
        colHideBtn: "readonly",
        locColHideBtn: "readonly",
        expandedLocations: "writable",

        // ── Breakdown / stripboard ────────────────────────────────────────────
        _getActiveBd: "readonly",
        _sbBuildSceneData: "readonly",
        _migrateBreakdowns: "readonly",
        _createBreakdown: "readonly",
        _makeDrop: "readonly",
        _acShow: "readonly",
        _acRemove: "readonly",
        _extractTextForBreakdown: "readonly",
        _stripFountainMarkup: "readonly",
        parseBreakdownScenes: "readonly",
        importBreakdownFromScript: "readonly",
        showBdScriptImporter: "readonly",
        scriptFileIcon: "readonly",
        _scoutIconHtml: "readonly",
        _pendingBdText: "writable",
        _pendingScriptFile: "writable",
        openScriptUploadModal: "readonly",

        // ── Scouting ─────────────────────────────────────────────────────────
        _activeScoutIdx: "writable",
        _scoutMinimized: "writable",
        _activeTechScoutIdx: "writable",
        _techScoutMinimized: "writable",

        // ── Moodboard ────────────────────────────────────────────────────────
        _currentMoodboardId: "writable",

        // ── Misc state ───────────────────────────────────────────────────────
        _activeSection: "writable",
        currentFileCategory: "writable",
        selectedFileIds: "readonly",
        _mfNewPersonCallback: "writable",

        // ── Files view ─────────────────────────────────────────────────────────
        _openCreateFolder: "readonly",
        openCreateFolder: "readonly",
        confirmCreateFolder: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", {
        varsIgnorePattern: "^_", // _prefixed functions are called from HTML onclick handlers
        argsIgnorePattern: "^_",
      }],
      "no-undef": "warn",
      "no-console": "off",
      "no-constant-condition": "warn",
      "no-debugger": "error",
    },
  },
];
